spring:
  datasource:
    url: jdbc:h2:mem:wot
    username: user
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      setting:
        trace: false
        web-allow-others: false